### ISSUE TITLE
Bug: missing source map errors in browser

### ISSUE THREAD

**Issue by dave2wave** [apache/tooling-trusted-release#98]
See apache/tooling-agenda/issues/113

We have 2 similar errors in ATR

**Comment by sbp** [comment]
Resolved in 5fd0dbbdbb337215b50fa79be17b70c7de050fbd. [The fix in BAT was to configure Vite](https://github.com/apache/tooling-agenda/commit/31d4fbb4d91301cbe0593b1f4240af935792ff89), but for ATR the fix is to configure TypeScript.

**Comment by dave2wave** [comment]
I'm seeing these errors still.

<img width="916" alt="Image" src="https://github.com/user-attachments/assets/9267a206-a07d-4410-ad69-de4498aed260" />

**Comment by sbp** [comment]
Resolved in e57d597ae9381b4b033a5c394dbc7609b185a6d0.

**Comment by dave2wave** [comment]
One more source map file to go:

<img width="380" alt="Image" src="https://github.com/user-attachments/assets/3a62899f-c17d-49b7-9aa4-3954718d5c58" />

**Comment by sbp** [comment]
Resolved in 1051f03108500a4266fa0d2c5e5619f13148253a.

**Comment by dave2wave** [comment]
Still wrong. Please look more closely at the screenshot.

**Comment by dave2wave** [comment]
There was a caching issue in Safari.
